/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CarPlay.framework/CarPlay
 */






@interface CPTemplate  (Swizzling)

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, retain) NSOperationQueue *deferredOperationQueue;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSUUID *identifier;
@property (nonatomic, retain) NSMutableArray *internalLeadingBarButtons;
@property (nonatomic, retain) NSMutableArray *internalTrailingBarButtons;
@property (nonatomic, retain) NSArray *leadingNavigationBarButtons;
@property (readonly) Class superclass;
//@property (nonatomic) <CPTemplateDelegate> *templateDelegate;
//@property (nonatomic, retain) <CPBaseTemplateProviding> *templateProvider;
@property (nonatomic, retain) NSArray *trailingNavigationBarButtons;
@property (nonatomic, retain) id userInfo;

+ (bool)supportsSecureCoding;


- (bool)barButton:(id)arg1 setImage:(id)arg2;
- (bool)barButton:(id)arg1 setTitle:(id)arg2;
- (bool)control:(id)arg1 setEnabled:(bool)arg2;
- (void)dealloc;
- (id)deferredOperationQueue;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (void)handleActionForControlIdentifier:(id)arg1;
- (id)identifier;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (NSMutableArray *)internalLeadingBarButtons;
- (NSMutableArray *)internalTrailingBarButtons;
- (NSArray *)leadingNavigationBarButtons;
- (void)setDeferredOperationQueue:(id)arg1;
- (void)setInternalLeadingBarButtons:(NSMutableArray *)arg1;
- (void)setInternalTrailingBarButtons:(NSMutableArray *)arg1;
- (void)setLeadingNavigationBarButtons:(NSArray *)arg1;
- (void)setTemplateDelegate:(id)arg1;
- (void)setTemplateProvider:(id)arg1;
- (void)setTrailingNavigationBarButtons:(NSArray *)arg1;
- (void)setUserInfo:(id)arg1;
- (id)templateDelegate;
- (void)templateDidAppear:(id)arg1 animated:(bool)arg2;
- (void)templateDidDisappear:(id)arg1 animated:(bool)arg2;
- (id)templateProvider;
- (void)templateWillAppear:(id)arg1 animated:(bool)arg2;
- (void)templateWillDisappear:(id)arg1 animated:(bool)arg2;
- (NSArray *)trailingNavigationBarButtons;
- (id)userInfo;

@end
